export const studentsData = [
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        gender: "Male" as const,
        studentId: "ST101",
        email: "john@example.com",
        phone: "9980870016",
        address: "123 Main Street",
        city: "Bangalore",
        pin: "560001",
        state: "Karnataka",
        country: "India",
        grade: "5",
        image:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    {
        id: 2,
        firstName: "Jane",
        lastName: "Smith",
        gender: "Female" as const,
        studentId: "ST102",
        email: "jane@example.com",
        phone: "9876543210",
        address: "MG Road",
        city: "Mysore",
        pin: "570001",
        state: "Karnataka",
        country: "India",
        grade: "6",
        image:
            "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
]